language: objective-c
osx_image: xcode8.1
env:
  - LC_CTYPE=en_US.UTF-8
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - set -o pipefail && swift test
notifications:
  email: false
